OD-319 [Fix] Users will not create a new data source column name on entry deletion
Fliplet/fliplet-widget-data-source pull request #114
Opened 2021-01-21 10:06 UTC by YaroslavOvdii

@sofiiakvasnevska 

## Issue
https://weboo.atlassian.net/browse/OD-319

## Description
Preventing the creation of the data source columns on entries delete by the `Backspace` or `Delete` button

## Screenshots/screencasts
https://share.getcloudapp.com/6quxjnlZ

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko @ivandevupp

2021-01-22 15:43 UTC, tonytlwu requested changes

2021-01-22 15:43 UTC, tonytlwu commented on js/spreadsheet.js
> +      if (window.event.key === 'Delete' || window.event.key === 'Backspace') {
Please add a comment to explain this

2021-01-26 10:32 UTC, YaroslavOvdii commented on js/spreadsheet.js
> +      if (window.event.key === 'Delete' || window.event.key === 'Backspace') {
@tonytlwu  Added comment.

2021-01-26 10:43 UTC, tonytlwu approved these changes
@sofiiakvasnevska This is ready for testing

Risk: Medium
Affected: Studio users managing data source entries
Verify: Users can edit and delete data source entries and without breaking data integrity

Squash and merge: Stop data source columns being created when entries are deleted

2021-01-26 11:08 UTC, merged