ID-1234 [Feat] UI for custom access rules
Fliplet/fliplet-widget-data-source pull request #157
Opened 2021-07-07 17:36 UTC by squallstar

![image](https://user-images.githubusercontent.com/574210/124804476-a39da380-df5a-11eb-8542-4ec050f1e267.png)

2021-07-08 15:25 UTC, tonytlwu approved these changes

2023-01-09 09:46 UTC, tonytlwu requested changes

2023-01-09 09:46 UTC, tonytlwu commented on templates/accessRule.interface.hbs
> +    <td colspan="5" class="align-baseline"><span class="label label-info"><i class="fa fa-code"></i> Custom rule</span> {{name}}</td>
```suggestion
    <td colspan="5" class="align-baseline"><span class="label label-default"><i class="fa fa-code"></i> Custom rule</span> {{name}}</td>
```

2023-01-09 09:46 UTC, tonytlwu commented on interface.html
> +                <h5>Rule name</h5>
```suggestion
                <h5>Security rule name</h5>
```

2023-01-09 09:46 UTC, tonytlwu commented on interface.html
> +                <p>The description for your custom rule. Write something handy to help you remember what this rule is about.</p>
```suggestion
                <p>Use a name to describe the security rule.</p>
```

2023-01-16 14:38 UTC, squallstar commented
Reimplemented by https://github.com/Fliplet/fliplet-widget-data-source/pull/208

2023-01-16 14:38 UTC, closed without merging