XOR-325[FEAT] Ensure user can see Cancel button on Create/Edit Security Rule
Fliplet/fliplet-widget-data-source pull request #179
Opened 2022-07-25 13:10 UTC by NikitaJadhavXoriant

**Product areas affected**
Widget Data Source -> App Data -> Select DataSource -> Security Rule -> Add/Edit security Rule -> Cancel button

**What does this PR do?**
In this PR we have added Cancel button for Create / Edit Security Rule dialog box. On click of Cancel button dialog box is closing.  

**JIRA ticket**
[click here](https://weboo.atlassian.net/browse/XOR-325)

**Result**
![image](https://user-images.githubusercontent.com/108272606/180784561-0aeb18c1-6ad8-4ac7-ac0c-9a090ff6878f.png)

**Checklist**
None

**Testing instructions**
None

**Deployment instructions**
None

**Author concerns**
None

2022-07-25 13:38 UTC, yogeshmsharma-xoriant approved these changes
remove unwanted lines, rest looks ok to me

2022-07-25 13:38 UTC, yogeshmsharma-xoriant commented on js/interface.js
> +
do we need this extra line?

2022-07-25 13:40 UTC, squallstar requested changes

2022-07-25 14:32 UTC, NikitaJadhavXoriant commented on js/interface.js
> +})
added semicolon please check now

2022-07-25 15:31 UTC, tonytlwu approved these changes

2022-07-26 13:21 UTC, squallstar approved these changes

2022-07-26 14:55 UTC, merged