XOR-281 [Feat] Reorder functionality added to DS Security Rules
Fliplet/fliplet-widget-data-source pull request #183
Opened 2022-08-22 08:17 UTC by NikitaJadhavXoriant

**Product areas affected**
Studio -> App Data -> Data Source -> Security Rules -> Reorder rules

**What does this PR do?**
Implemented reorder functionality in DS Security Rules

**JIRA ticket**
[JIRA](https://weboo.atlassian.net/browse/XOR-281)

**Result**

![image](https://user-images.githubusercontent.com/108272606/185873481-5474333c-0b0d-4b31-8818-46647a5bd9c8.png)

**Checklist**
none

**Testing instructions**
none

**Deployment instructions**
none

**Author concerns**
none

2022-08-22 09:15 UTC, squallstar commented
@tonytlwu the way the UI has been laid out looks like I am sorting rules by status, whereas they are just sorted by order. I would have suggested the sorting happens on a new column called "Order", which shows a tooltip to the user explaining the reasons a user may want to sort rules.

This aside, the changes in the PR look fine from my point of view.

2022-08-25 09:26 UTC, tonytlwu requested changes
Doesn't meet new coding standard

2022-08-25 09:26 UTC, tonytlwu commented on css/interface.css
> +}
Empty line between style declarations ([ref](https://docs.google.com/document/d/1XPlQHPbqp3rGGTekcC05bKtwKDDjrU2RMJ4VIHLXp64/edit#heading=h.q74tthq28fj3))

2022-08-25 14:57 UTC, NikitaJadhavXoriant commented on css/interface.css
> +}
Empty line has been added as per new coding standards. Please review

2022-08-25 15:17 UTC, tonytlwu approved these changes

2022-08-25 15:17 UTC, merged