XOR-276 [FEAT] Ensure access and edition to a DS in DSM by a studio user for live app
Fliplet/fliplet-widget-data-source pull request #194
Opened 2022-09-26 12:19 UTC by NikitaJadhavXoriant

**Product areas affected**

Studio -> App Data -> Open DS -> Message for live app DS changes

**What does this PR do?**

Implemented functionality to show warning message if app is live and changes made to DS

**JIRA ticket**

[click here](https://weboo.atlassian.net/browse/XOR-276)

**Result**

![XOR-276-1](https://user-images.githubusercontent.com/108272606/192273646-cd7c6955-7772-4f05-8fc9-1b76fcdf74df.JPG)

**Checklist**

 None

**Testing instructions**

None

**Deployment instructions**

None

Author concerns

None

2022-09-26 12:27 UTC, amolsuryawanshi47 commented on js/interface.js
> +/**
Missing JSDoc @returns for function

2022-09-26 12:27 UTC, amolsuryawanshi47 commented on js/interface.js
> +/**
Missing JSDoc @returns for function

2022-09-26 13:03 UTC, amolsuryawanshi47 approved these changes
changes looks ok to me

2022-09-26 16:20 UTC, tonytlwu requested changes
Does not meeting coding standards. ESlint issues not fixed.

2022-09-26 17:48 UTC, NikitaJadhavXoriant commented
> Does not meeting coding standards. ESlint issues not fixed.

Coding standards issue resolved.

2022-09-26 17:48 UTC, NikitaJadhavXoriant commented on js/interface.js
> +/**
Added

2022-09-26 17:48 UTC, NikitaJadhavXoriant commented on js/interface.js
> +/**
Added

2022-09-26 17:49 UTC, amolsuryawanshi47 approved these changes

2022-09-27 08:01 UTC, amolsuryawanshi47 approved these changes
Looks ok to me

2022-09-27 09:28 UTC, tonytlwu requested changes

2022-09-27 09:28 UTC, tonytlwu commented on js/interface.js
> +  getApps.then(function(apps) {
This isn't how we should be determining whether a data source is connected to a live app. I'll update the tech spec with more information.

2022-09-27 10:40 UTC, NikitaJadhavXoriant commented on js/interface.js
> +if (widgetData.appId) {
Hi @tonytlwu , yes you are correct, above code is not related to XOR-276, but after taking latest from master branch of Data Source widget (which involved XOR-203 changes), Kathi found one issue while testing, so to quick fix that issue Amol gave above solution, so I added above code.

2022-09-27 10:42 UTC, NikitaJadhavXoriant commented on js/interface.js
> +    this.currentAppPublishStatus = false;
Hi @tonytlwu, I was misunderstood the scope. I will remove 'this' and update the PR.

2022-09-27 13:11 UTC, NikitaJadhavXoriant commented on js/interface.js
> +if (widgetData.appId) {
Hi @tonytlwu, we have created new ticket for above issue  #XOR-566, and it's handled separately. So, removing above changes from this PR.

2022-09-27 13:11 UTC, NikitaJadhavXoriant commented on js/interface.js
> +    this.currentAppPublishStatus = false;
Done changes in PR

2022-09-27 13:17 UTC, NikitaJadhavXoriant commented on js/interface.js
> +    var currentApp = _.find(apps, function(app) {
Updated code accordingly.

2022-09-30 05:56 UTC, amolsuryawanshi47 approved these changes
Changes looks ok to me

2022-09-30 08:38 UTC, tonytlwu requested changes
Does not meet coding standards

2022-09-30 15:56 UTC, tonytlwu requested changes
The change requests don't need another round of QA

2022-09-30 15:56 UTC, tonytlwu commented on js/interface.js
> +    if (dataSource.apps && dataSource.apps.length > 0) {
```suggestion

    if (dataSource.apps && dataSource.apps.length > 0) {
```

2022-09-30 15:56 UTC, tonytlwu commented on js/interface.js
> +var isPublishedApp = false;
```suggestion
var dataSourceIsLive = false;
```

2022-09-30 17:49 UTC, NikitaJadhavXoriant commented on js/interface.js
> +    if (dataSource.apps && dataSource.apps.length > 0) {
Done

2022-09-30 17:49 UTC, NikitaJadhavXoriant commented on js/interface.js
> +var isPublishedApp = false;
Done

2022-10-03 01:08 UTC, amolsuryawanshi47 approved these changes
Changes looks ok to me

2022-10-04 15:23 UTC, merged